### ISSUE TITLE
Map css class name to symbol

### ISSUE THREAD

**Issue by AlexHedley** [andreinitescu/IconFont2Code#1]
Might be too specific but for example I’m using [Font Awesome](https://origin.fontawesome.com/) in a web app.

I have a config page which allows you to select an icon via a picker.
[Icon Picker](https://farbelous.io/fontawesome-iconpicker/)

This saves the class name (“star”) not the code (“\uf641”).
When I use an api to retrieve this info and display in my Xam app I’d like to use the correct symbol based on the corresponding class name.

- Example in Xam: [Using Font Icons in Xamarin.Forms: Goodbye Images, Hello Fonts!](https://montemagno.com/using-font-icons-in-xamarin-forms-goodbye-images-hello-fonts/)

[A list of Font Awesome icons and their CSS content values](http://astronautweb.co/snippet/font-awesome/)

Feature Request:
Pick a font and a css file and the tool generates a KVP or Dict that stores the mapping.

**Comment by andreinitescu** [comment]
Sorry, it's indeed too specific for the scope of this tool. Since this tool is open source you can fork it and modify it any way you'd like.

**Comment by AlexHedley** [comment]
No problem at all, just thought I'd bring it up in case it was a roadmap item and didn't want to duplicate work, I'll let you know how I get on, thanks for a great tool.

**Comment by andreinitescu** [comment]
Reading again your description, I want to be sure I understand it correctly. 
The tool already can take a CSS file and generate the C# code based on the glyph name from the CSS. Isn't this what you want?
I initially thought you are referring to the CSS support in Xamarin Forms.

Could you please provide a clear example of what you mean? 
Something like: 
Step 1: select a font file
Step 2: ...

**Comment by AlexHedley** [comment]
I'd missed the css upload part, so apologies for that.

For instance, I upload `FontAwesome.otf`
If I filter for a single item for a example:

**Glass**
https://fontawesome.com/v4.7.0/icon/glass

```csharp
static class IconFont
{
	public const string Glass = "\uF000";
}
```

Adding `font-awesome.css` produces

```csharp
static class IconFont
{
	public const string FaGlass = "\uF000";
}
```

So that will work.

**Comment by andreinitescu** [comment]
Awesome!!! 
Let me know what if there's anything you think I can do in order to better communicate this important feature. It's described in the README and there's also a tool-tip on the "what's this for"

![image](https://user-images.githubusercontent.com/743918/57061438-793e6480-6cc5-11e9-8d5c-cdca73671f71.png)

Someone else asked me about how the CSS feature works, so maybe there's something which I can improve.

**Comment by andreinitescu** [comment]
I (think) I improved the explanation for the CSS feature, check it out:


![image](https://user-images.githubusercontent.com/743918/57063611-7f840f00-6ccc-11e9-9359-9dfdb11b5753.png)

**Comment by AlexHedley** [comment]
I think the popup is a great addition
