### ISSUE TITLE
Can you handle duplicates?

### ISSUE THREAD

**Issue by sturlath** [andreinitescu/IconFont2Code#10]
I was trying out [www.nerdfonts.com](https://www.nerdfonts.com) and it creates about 400 duplicate errors if I take it all. It would be great if the tool could auto post-fix-increment the C# class like

`
        public const string Plus = "\uf067";
        public const string Plus_2 = "\uf44d";
        public const string Plus_3 = "\uf914";
`

Or something like that :-)

**Comment by andreinitescu** [comment]
Could you please attach a font file sample with duplicates please? Ideally, something small would be great, otherwise anything else is fine too.

**Comment by andreinitescu** [comment]
Oh, do you mean the font file has glyphs with duplicate names? (which is why IconFont2Code generates duplicate C# properties)

**Comment by andreinitescu** [comment]
Like I said, please attach a font file sample, so I can try think for a fix. Thanks

**Comment by andreinitescu** [comment]
Should be working now

**Comment by sturlath** [comment]
Hi sorry was going to send you an example but couldn't get to it until now. Thank you for your update. I just tried it out and it works like a charm :-)

**Comment by andreinitescu** [comment]
Awesome! Thanks for reporting the issue 👍 Let me know if you find anything else. Thanks
