### ISSUE TITLE
Suggested Feature

### ISSUE THREAD

**Issue by alanhoman** [andreinitescu/IconFont2Code#11]
This tool has been very helpful!  Thank you for your great work.  I had one simple suggestion and that is to automatically add a comment in the C# generated code as shown below.  

//Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code/
static class IconFont
{
...
}

**Comment by andreinitescu** [comment]
Happy to hear it's been helpful. Just curious, how would adding that comment be useful?

**Comment by alanhoman** [comment]
Hi Andrei,

This would help in 2 ways:


  1.  It would document how this code was generated so another developer could see the source and know how to refresh it or create a new one when necessary.  I would manually add this to the code in any case for the same reason.
  2.  If someone uses your tool and adds their code to GitHub, other users will see the comment and know how the code was generated (so they could do it themself for future updates).  I noticed your code in https://github.com/davidortinau/Xappy and had to dig around to figure out how they generated this code.  If the comment had been there, I would have known immediately.

Thanks,
Alan

**Comment by andreinitescu** [comment]
@alanhoman Done! Thanks for reply
