### ISSUE TITLE
Invalid field names get generated.

### ISSUE THREAD

**Issue by Andrew-Oliveira** [andreinitescu/IconFont2Code#12]
**Problem:**

Invalid field names can get generated. (Specifically field names beginning with a number.)

**Reproduction Steps:**
1. Upload font. https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.ttf
2. The following field will get generated: `public const string 6_ft_apart = "\uf21e";`

**Suggested Fix:**

Prefix any field that would start with a numeric value with an underscore. `public const string _6_ft_apart = "\uf21e";`

**Comment by andreinitescu** [comment]
Hi Andrew! 
Many thanks for reporting this. It should be fixed now
