### ISSUE TITLE
File upload does not work in MS Edge on MacOS

### ISSUE THREAD

**Issue by MSicc** [andreinitescu/IconFont2Code#16]
Once I selected the font file, the site keeps saying 'Loading' and does nothing else.

Can't even open dev tools to investigate the issue further as the browser blocks it with a non reacting message.

**Comment by andreinitescu** [comment]
What font are you using?

**Comment by MSicc** [comment]
I tried both the webfont and the ttf file from materialdesignicons.com

**Comment by andreinitescu** [comment]
Maybe try to wait a little bit more? 😀
No idea about MS Edge but it works great in Safari
![image](https://user-images.githubusercontent.com/743918/111324165-32687680-8673-11eb-9142-d4caa2420e2a.png)

**Comment by andreinitescu** [comment]
I can only guess this is not an issue 🤷‍♂️

**Comment by MSicc** [comment]
I know it works with Safari, but my primary browser is Edge. If it would just take a little longer then I wouldn't even open this issue.

I understand now that you are not going to support Edge on MacOS.
