### ISSUE TITLE
Cannot open Font Awesome 6 otf file.

### ISSUE THREAD

**Issue by charliebrowncpt** [andreinitescu/IconFont2Code#20]
Hello,

I'm trying to open a Font Awesome 6 iconset. Attached is is the .otf file I'm using. 
The error is shown below. Do you know what the issue is?
![image](https://github.com/andreinitescu/IconFont2Code/assets/61466046/adc574c7-97ce-43ae-88d7-894f07d0279d)

This is the font file I'm trying to convert. 
[Font Awesome 6 Free-Regular-400.zip](https://github.com/andreinitescu/IconFont2Code/files/13034259/Font.Awesome.6.Free-Regular-400.zip)

I checked the dev tools in Edge and saw that it's missing openType.
![image](https://github.com/andreinitescu/IconFont2Code/assets/61466046/a9cdd272-1d5d-4b75-ade0-3dd76e88c46e)

Charles

**Comment by andreinitescu** [comment]
Hi, Thanks for taking the time to report this.

It works fine for me. What browser and OS are you using?

![image](https://github.com/andreinitescu/IconFont2Code/assets/743918/38978ac4-2fa1-40c0-9a94-37ba584e7633)

**Comment by charliebrowncpt** [comment]
Hi Andrei,

I'm using Win 11 and Edge. Let me try another browser and let you know.
Thanks for getting back to me :)

Charles

**Comment by andreinitescu** [comment]
FYI, I'm on Windows 10 and I tested it on Edge, Firefox and Chrome.

Does the error reproduce every time you open the browser and choose the font?

**Comment by andreinitescu** [comment]
Hi @charliebrowncpt, could you please say whether it works for you or not? I doubt Win11 or Win10 make any difference, it's all about the web-browser.

**Comment by andreinitescu** [comment]
Not clear to me this is an issue or not. Please reopen if it's actually an issue and provide more info. Thanks.

**Comment by charliebrowncpt** [comment]
Hi Andrei,

Sorry for the late reply - I'm under pressure to get a massive project live
next week, so haven't had the chance to reply.

I'll reopen the issue after I do more testing and if I find something.
