### ISSUE TITLE
Ability to support woff2

### ISSUE THREAD

**Issue by craig-acutest** [andreinitescu/IconFont2Code#21]
Hi, thanks for creating this tool think it is really useful, and have used it on quite a few projects.

Is it possible to add support for the .woff2 format? Had a colleague say the tool was not helpful to them, due to this. So I showed them how to convert, via another tool, the woff2 file to a woff file.

But would be awesome if this tool could accept .woff2 as a input, and either convert to woff, or parse it as is.

Thanks, Craig.

**Comment by andreinitescu** [comment]
Hey Craig, 

Thanks for your suggestion. I will see what I can do, it requires some work.

**Comment by andreinitescu** [comment]
@craig-acutest woff2 support is implemented, I did some little testing and it seems to work.

I will close this one, let me know if there's still an issue. Thanks.

**Comment by craig-acutest** [comment]
Wow amazing, thanks very much!!
