### ISSUE TITLE
Throwing error when trying to upload materialdesign font

### ISSUE THREAD

**Issue by ithiredguns** [andreinitescu/IconFont2Code#8]
![iconsfont2code_issue](https://user-images.githubusercontent.com/27841167/72273730-ddf1e300-35f8-11ea-87de-5049c0f9508d.jpg)

Not able to use the link with any font...

**Comment by andreinitescu** [comment]
Can you please point to the font you are using?

**Comment by andreinitescu** [comment]
I just tested with
https://github.com/google/material-design-icons/blob/master/iconfont/MaterialIcons-Regular.ttf
and it works fine.

I'm closing this for now, please reopen with a link to the exact font you try to use.

**Comment by frogcrush** [comment]
I'm also having this issue, it shows the error: "Unable to read the ijmap file. Make sure its format is valid."

**Comment by leocdi** [comment]
> I'm also having this issue, it shows the error: "Unable to read the ijmap file. Make sure its format is valid."

Experiencing same issue.
![image](https://user-images.githubusercontent.com/29575216/102821903-408e5a00-43d8-11eb-9dac-fe8e2d3db22e.png)

Used this set :  https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.ttf

**Comment by andreinitescu** [comment]
@frogcrush Thanks for reporting.

**Comment by jj-apps** [comment]
I'm also having issues with this material design font:
https://github.com/google/material-design-icons/blob/master/font/MaterialIconsOutlined-Regular.otf

It just gets stuck on the "Loading" overlay.

**Comment by andreinitescu** [comment]
Didn't think much people are using this tool anymore.

Anyway, it should work, let me know.

**Comment by jj-apps** [comment]
Works great! Thank you.

> Didn't think much people are using this tool anymore.
> 
> Anyway, it should work, let me know.

**Comment by andreinitescu** [comment]
@frogcrush I guess it works for you too, so I am closing this
