### ISSUE TITLE
[Code Generation] Wrong literals for glyphs from upper bit planes.

### ISSUE THREAD

**Issue by CarnageMarkus** [andreinitescu/IconFont2Code#9]
Some characters doesn't work because code is not generated properly for C#.

https://stackoverflow.com/questions/31690885/unicode-special-character-not-displaying-in-label

> The \u escape takes only 4 hex digits

Trying to use `\u0001F6B5` will result in multiple wrong characters
Proper code should be `\U0001F6B5` for codes longer than 4 hex digits

**Comment by andreinitescu** [comment]
Which font are you using? I need to know in order to test and fix the issue. Thanks.

**Comment by andreinitescu** [comment]
@CarnageMarkus Should be fixed now. Could you please confirm it works for you too? Thanks

**Comment by CarnageMarkus** [comment]
I was using Material Design Icons, I will let you know in a minute.

**Comment by CarnageMarkus** [comment]
Everything works. Thanks. :)

**Comment by andreinitescu** [comment]
@CarnageMarkus Great, thanks for raising the issue.

**Comment by matt-goldman** [comment]
Hi @andreinitescu - I've noticed since this change all characters are displayed with upper bit plane formatting for this particular font (Material Design Icons).
<img width="777" alt="iconfontscreen" src="https://user-images.githubusercontent.com/19944129/100527362-f9bca280-3225-11eb-8ed2-b4e89d0b94d4.png">

**Comment by andreinitescu** [comment]
@matt-goldman So what's the issue? Does the icons get displayed in your app?

**Comment by matt-goldman** [comment]
> @matt-goldman So what's the issue? Does the icons get displayed in your app?

The icons don't display in my app using these codes, no. If I use the lower bit plane codes produced by your previous version, they work. I think this font uses a combination of both.

**Comment by matt-goldman** [comment]
@andreinitescu have you had a chance to look at this yet, were you able to reproduce this issue?

**Comment by matt-goldman** [comment]
One last comment on this - looks like the latest version of this font does in fact encode all of the characters with upper bitplane codes. So it's not a bug in your code, just a change in the way this font is organized.
